import Project from "@/ui/Project"
import project1 from "@/assets/png/RAG.webp"
import project2 from "@/assets/png/java.jpg"
function Projects() {
    const projects = [
        {
            path: project1,
            title: "RAG Assistant",
            content: `This project develops an intelligent question-answering system based on the RAG architecture.\n 
            The system allows users to ask questions, receive answers generated by a Large Language Model (LLM) combined with information retrieved from internal documents. \n
            The pipeline includes several stages: document loading and preprocessing, converting text into vector embeddings, storing them in a vector database, retrieving the most relevant document chunks based on the user’s query, and finally generating a context-aware answer using the language model. \n
            This approach enables the model to leverage external knowledge from custom datasets rather than relying solely on its pretrained knowledge, thereby improving accuracy and keeping the system’s information more up-to-date.`,
            tech: ["Django", "React", "Olamma"]
        },
        {
            path: project2,
            title: "Bookstore management system",
            content: "This project develops a bookstore management system designed to support the daily operations of a book retail store. The system provides features for managing books, categories, authors, publishers, customers, employees, and sales invoices. It allows staff to easily perform tasks such as adding, updating, searching, and deleting book records, as well as processing sales transactions and tracking inventory. The application also includes role-based access control to manage user permissions for different functions. By organizing data efficiently and automating common tasks, the system helps improve store management efficiency, reduce manual work, and ensure accurate record keeping.",
            tech: ["Java", "MySQL"]
        },
        // {
        //     path: project1,
        //     content: "This is my first project This is my first project, this is my first project, this is my first project",
        // },
    ];
    return (
        <div className="flex flex-col items-center gap-8 w-full md:px-10">
            <div className="text-2xl font-black text-accent md:text-4xl">Projects</div>
            <div className="flex flex-col items-center gap-8 w-full">
                {projects.map(item => (<Project path={item.path} title={item.title} content={item.content} tech={item.tech}></Project>))}
            </div>
        </div>
    )
}
export default Projects